# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fwdNN2 <- function(X, model) {
    .Call(`_dnn_fwdNN2`, X, model)
}

bwdNN2 <- function(dy, cache, model) {
    .Call(`_dnn_bwdNN2`, dy, cache, model)
}

optimizerMomentum <- function(V, dW, W, alpha = 0.63, lr = 0.0001, lambda = 1.0) {
    .Call(`_dnn_optimizerMomentum`, V, dW, W, alpha, lr, lambda)
}

optimizerNAG <- function(V, dW, W, alpha = 0.63, lr = 0.0001, lambda = 1.0) {
    .Call(`_dnn_optimizerNAG`, V, dW, W, alpha, lr, lambda)
}

optimizerAdamG <- function(V1, V2, dW, W, epoch, beta1 = 0.9, beta2 = 0.999, lr = 0.0001, lambda = 1.0) {
    .Call(`_dnn_optimizerAdamG`, V1, V2, dW, W, epoch, beta1, beta2, lr, lambda)
}

dnnFit2 <- function(X, y, model, control) {
    .Call(`_dnn_dnnFit2`, X, y, model, control)
}

